# Generated by Django 4.1 on 2022-08-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterInfo',
            fields=[
                ('meter_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('install_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(max_length=10)),
                ('current', models.FloatField(max_length=10)),
                ('inst_power', models.FloatField(max_length=10)),
                ('power_factor', models.FloatField(max_length=10)),
                ('frequency', models.FloatField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('meter_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='energydata.meterinfo')),
            ],
        ),
    ]
